project:
  type: website
  output-dir: docs

website:
  title: "Mohammad Nasirpour"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
    right:
      - icon: envelope
        href: mailto:m.h.nasirpour@gmail.com
      - icon: github
        href: https://github.com/Mhn1124

format:
  html:
    theme: flatly
    css: styles.css
